# Generated by Django 5.1.2 on 2024-11-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_head', models.CharField(max_length=50)),
                ('department_loc', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('amount_donated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
                ('status_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('title', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('advisors', models.ManyToManyField(related_name='projects', to='rms_app.advisor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rms_app.department')),
                ('researchers', models.ManyToManyField(related_name='projects', to='rms_app.researcher')),
                ('sponsors', models.ManyToManyField(related_name='projects', to='rms_app.sponsor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rms_app.status')),
            ],
        ),
    ]
