# Generated by Django 5.1.2 on 2024-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
