# Generated by Django 5.1.2 on 2024-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0002_alter_researcher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='advisors',
            field=models.ManyToManyField(related_name='research_projects', to='rms_app.advisor'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='researchers',
            field=models.ManyToManyField(related_name='research_projects', to='rms_app.researcher'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='sponsors',
            field=models.ManyToManyField(related_name='research_projects', to='rms_app.sponsor'),
        ),
    ]
