# Generated by Django 5.1.2 on 2024-11-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0003_alter_researchproject_advisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
