# Generated by Django 5.1.2 on 2024-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0004_alter_sponsor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
