# Generated by Django 5.1.3 on 2024-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0006_advisor_user_researcher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
