# Generated by Django 5.1.2 on 2024-12-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0007_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
