# Generated by Django 5.1.2 on 2024-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0009_alter_advisor_email_alter_researcher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='amount_donated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
