# Generated by Django 5.1.2 on 2024-12-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0011_sponsor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='user',
        ),
    ]
